### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [featurist/PogoScript.tmbundle#1]
I would like to use your grammar for PogoScript but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@refractalize @joshski Did you get a chance to look into this? I'm considering using your grammar at [github/linguist](https://github.com/github/linguist) to highlight PogoScript code on GitHub.

**Comment by refractalize** [comment]
Hi @pchaigno, I've just uploaded the MIT license, so feel free, github highlight support would be awesome!

**Comment by pchaigno** [comment]
Great! Thanks!
I'll tell you if it's your grammar that's chosen to highlight PogoScript on GitHub.

**Comment by pchaigno** [comment]
@refractalize Your grammar is now used to highlight PogoScript code on GitHub (files and code snippets in Markdown)! (See github/linguist#2089 for more information.)

**Comment by refractalize** [comment]
Nice one!
